[package]
name = "x86_intr"
version = "0.2.1"
edition = "2021"
rust-version = "1.96"
documentation = "https://docs.rs/x86_intr"
repository = "https://github.com/bobbothe2nd/x86_intr"
description = "Additional x86_64 intrinsics"
license = "MIT"
keywords = ["intrinsics", "intstructions", "x86", "x86_64"]
categories = ["algorithms", "hardware-support", "no-std", "no-std::no-alloc"]

[dependencies.intr_gen]
version = "0.1.0"
path = "../intr_gen"
